services:
  web:
    container_name: web_app_container
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/images/Dockerfile
    networks:
      - uvlhub_network
    entrypoint: ["/app/scripts/wait-for-db.sh"]
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--reload", "--debug"]    
  db:
    container_name: mariadb_container
    image: mariadb:12.0.2
    env_file:
      - ../.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - uvlhub_network

volumes:
  db_data:

networks:
  uvlhub_network:
